<a href="https://colab.research.google.com/github/AkashRanjan-nie/DAV/blob/main/experiment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import numpy as np
import pandas as pd

In [4]:
# Create a NumPy array
arr = np.array([78, 92, 65, 84, 71])

# Display the array
print("Array:", arr)

# Calculate mean
print("Mean:", arr.mean())

# Reshape into 2D array
print("Reshaped 2D:")
print(arr.reshape(5, 1))

# Slice elements from index 1 to 3
print("Sliced (index 1 to 3):", arr[1:4])

Array: [78 92 65 84 71]
Mean: 78.0
Reshaped 2D:
[[78]
 [92]
 [65]
 [84]
 [71]]
Sliced (index 1 to 3): [92 65 84]

In [5]:
# Create student data
data = {
    "Student": ["Arjun", "Meera", "Vikram", "Neha"],
    "Attendance": [85, 92, 78, 95],
    "Score": [76, 89, 68, 94]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print("Student Data:")
display(df)

Student Data:

  Student  Attendance  Score
0   Arjun          85     76
1   Meera          92     89
2  Vikram          78     68
3    Neha          95     94

In [6]:
print("First two rows:")
display(df.iloc[0:2])

First two rows:

  Student  Attendance  Score
0   Arjun          85     76
1   Meera          92     89

In [7]:
print("Score column:")
display(df["Score"])

Score column:

0    76
1    89
2    68
3    94
Name: Score, dtype: int64

In [8]:
print("Rows where Score > 80:")
display(df[df["Score"] > 80])

Rows where Score > 80:

  Student  Attendance  Score
1   Meera          92     89
3    Neha          95     94